CustomerDataApi/Controllers/CustomersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CustomerDataApi.Data;
using CustomerDataApi.Models;
using CustomerDataApi.Controllers;

namespace CustomerDataApi.Controllers
{
    public class CustomersController : Controller
    {
        private ApplicationDbContext _context;

        public CustomersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
              return View(await _context.Customers.ToListAsync());
        }

        // GET : Customers/SearchCustomer
        public async Task<IActionResult> SearchCustomer() {
            return View();
        }

        // POST: Customers/SearchResult/name
        [HttpPost]
        public async Task<IActionResult> SearchResult(string name)
        {
            Console.WriteLine("*****************************************************************");
            Console.WriteLine(name);
            Console.WriteLine("*****************************************************************");

            var customer = await _context.Customers.FindAsync(name);
            if (customer == null)
            {
                return NotFound();
            }
            return View();
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("_id,index,age,eyeColor,name,gender,company,email,phone,about,registered,latitude,longitude")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Edit
        public async Task<IActionResult> Edit()
        {
            return View(await _context.Customers.ToListAsync());
        }

        // GET: Customers/EditCustomer
        [HttpGet]
        public async Task<IActionResult> EditCustomer(string id)
        {
            if (id == null || _context.Customers == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m._id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCustomer(string _id, string name, [Bind("_id,index,age,eyeColor,name,gender,company,email,phone,about,registered,latitude,longitude")] Customer customer)
        {
            if (_id != customer._id)
            {
                Console.WriteLine("******************************** id not match *********************************");
                return NotFound();
            }

            else if (_id == customer._id)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                    Console.WriteLine("******************************** updated *********************************");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer._id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        Console.WriteLine("******************************** error *********************************");
                        throw;
                    }
                }
                return RedirectToAction(nameof(EditCustomer));
            }
                
            return View(customer);
            
        }

        // GET: Customers/Edit
        public async Task<IActionResult> Distance()
        {
            return View(await _context.Customers.ToListAsync());
        }

        // POST: Customers/GetDistance/id
        [HttpGet]
        public async Task<IActionResult> GetDistance(string id) 
        {
            string distance;
            string customerName;

            if (id == null || _context.Customers == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);

            if (customer == null)
            {
                return NotFound();
            }
            else {
                string latitude = customer.latitude;
                string longitude = customer.longitude;
                customerName = customer.name;

                distance = CalcDistance.findDistance(latitude, longitude);
            }

            

            ViewBag.Distance = distance;
            ViewBag.CustomerName = customerName;
            return View();
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Customers == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m._id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Customers == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Customers'  is null.");
            }
            var customer = await _context.Customers.FindAsync(id);
            if (customer != null)
            {
                _context.Customers.Remove(customer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(string id)
        {
          return _context.Customers.Any(e => e._id == id);
        }
    }
}

CustomerDataApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CustomerDataApi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CustomerDataApi.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CustomerDataApi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CustomerDataApi
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>